#
# Hi, thanks for trying out LightningUtils!
# This is the configuration file for the plugin.
#


# Specify which commands are enabled and the
# aliases that can be used for them.
# All permission nodes specified below are
# prefixed with "lightningutils.". If
# the permission is empty ('') then everyone
# has access to the command.
commands:
  send:
    enabled: true
    permission: 'send'
    aliases:
      - 'send'
      - 'transfer'

  alert:
    enabled: true
    permission: 'alert'
    aliases:
      - 'alert'

  lobby:
    enabled: true
    permission: ''
    aliases:
      - 'lobby'
      - 'hub'

  staffchat:
    enabled: true
    permission: 'staffchat'
    aliases:
      - 'staffchat'
      - 'sc'

  sudo:
    enabled: true
    permission: 'sudo'
    aliases:
      - 'sudo'

  find:
    enabled: true
    permission: 'find'
    aliases:
      - 'find'


# The fallback chain of where to send players
# when they are kicked from a server.
#
# This list will be applied when they are
# kicked while online, when they join a server,
# and when they join the network.
#
# In this example below the players will by
# default be kicked to the "lobby" server and,
# if they are kicked from the "lobby" server
# they will be sent to the "limbo" server. But
# if they are kicked from the "limbo" server
# they will be kicked from the network.
fallback:
  enabled: true
  default_server: 'lobby'
  servers:
    lobby:
      kick: false
      fallback: 'limbo'
    limbo:
      kick: true
      fallback: ''


lobby:
  # Order to send players in.
  # random: Send players to a random lobby.
  # priority: Send players to the lobby with
  #   the least players.
  #
  # Valid lobbies are checked with regex.
  order: 'priority'
  valid_lobbies:
    - 'lobby-[0-9]+'

staffchat:
  enabled: true
  # Whether to allow toggling the staff chat if
  # no message is provided.
  # To use this, the server might have to have the
  # SignedVelocity plugin installed.
  allow_toggle: true
  # Whether to allow prefixing the message with
  # a certain string will send the message to the
  # staff chat.
  # To use this, the server might have to have the
  # SignedVelocity plugin installed.
  allow_prefix: true
  # The prefix to use for the staff chat.
  prefix: '$'

sudo:
  # Whether to have the player sudo'd notified that
  # they were forced to execute a command.
  notify: false

config_version: 1.0